name: fmt

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install lint tools
        run: pdm install -G lint

      - name: Auto-fix (lint + format)
        run: pdm run lintfmt

      - name: Ensure working tree clean
        run: git diff --exit-code
